CREATE DATABASE rivalry;

USE rivalry;

CREATE OR REPLACE TABLE item
  (id INTEGER AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(256) NOT NULL,
   CREATE OR REPLACEd_date TIMESTAMP NOT NULL DEFAULT NOW());

CREATE OR REPLACE TABLE artist
(id INTEGER AUTO_INCREMENT PRIMARY KEY,
 first_name VARCHAR(256) NOT NULL,
 last_name VARCHAR (256),
 CREATE OR REPLACEd_date TIMESTAMP NOT NULL DEFAULT NOW());
                                                                           
CREATE OR REPLACE TABLE item_artist
(id INTEGER AUTO_INCREMENT PRIMARY KEY,
 artist_id INTEGER NOT NULL,
 item_id INTEGER NOT NULL,
 CREATE OR REPLACEd_date TIMESTAMP NOT NULL DEFAULT NOW());

CREATE OR REPLACE TABLE catalog
(id INTEGER AUTO_INCREMENT PRIMARY KEY ,
 issue_number INTEGER NOT NULL,
 issue_tag_line VARCHAR(520),
 theme_id INTEGER,
 CREATE OR REPLACEd_date TIMESTAMP NOT NULL DEFAULT NOW());







